/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#ebe1d0",
        "primary-container": "#164491",
        "on-primary-fixed-variant": "#154390",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "tertiary-container": "#6a3c00",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-surface": "#353025",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#822708",
        "on-tertiary-fixed-variant": "#693c00",
        "on-secondary-container": "#721d00",
        "background": "#fff8f1",
        "inverse-on-surface": "#faf0de",
        "tertiary": "#4a2900",
        "on-secondary": "#ffffff",
        "outline": "#747782",
        "on-primary-container": "#96b5ff",
        "primary-fixed": "#d9e2ff",
        "secondary": "#a23e1e",
        "primary-fixed-dim": "#afc6ff",
        "outline-variant": "#c3c6d3",
        "on-background": "#1f1b11",
        "surface-tint": "#345caa",
        "on-secondary-fixed": "#3a0a00",
        "on-tertiary-fixed": "#2c1600",
        "secondary-container": "#fe835d",
        "primary": "#002e6e",
        "surface-container": "#f7eddc",
        "surface-dim": "#e3d9c8",
        "on-surface": "#1f1b11",
        "surface-container-low": "#fdf2e1",
        "surface-container-highest": "#ebe1d0",
        "surface-bright": "#fff8f1",
        "tertiary-fixed": "#ffdcbe",
        "on-surface-variant": "#434651",
        "secondary-fixed": "#ffdbd1",
        "inverse-primary": "#afc6ff",
        "surface-container-high": "#f1e7d6",
        "secondary-fixed-dim": "#ffb59f",
        "on-tertiary-container": "#fea030",
        "surface": "#fff8f1",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#001944",
        "tertiary-fixed-dim": "#ffb870"
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
